In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
#read data we want to apply some agg
#a csv on white wine

df_wines = pd.read_csv('winequality-white.csv', sep=';')

#check some data
df_wines.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [3]:
#create a function to agg
def max_to_min(arr):
    return arr.max() - arr.min()


#use agg ang emplement fuction
df_wines.agg(max_to_min)

fixed acidity            10.40000
volatile acidity          1.02000
citric acid               1.66000
residual sugar           65.20000
chlorides                 0.33700
free sulfur dioxide     287.00000
total sulfur dioxide    431.00000
density                   0.05187
pH                        1.10000
sulphates                 0.86000
alcohol                   6.20000
quality                   6.00000
dtype: float64

In [4]:
#if you group by quality then agg you get
wwines = df_wines.groupby('quality')

wwines.agg(max_to_min)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
quality,,,,,,,,,,,
3,7.6,0.470,0.26,15.50,0.222,284.0,421.0,0.00900,0.68,0.46,4.6
4,5.4,0.990,0.88,16.85,0.277,135.5,262.0,0.01120,0.89,0.62,5.1
5,5.8,0.805,1.00,22.90,0.337,129.0,335.0,0.01519,1.00,0.61,5.6
6,10.4,0.885,1.66,65.10,0.240,109.0,276.0,0.05140,1.09,0.83,5.5
7,5.0,0.680,0.73,18.35,0.123,103.0,195.0,0.01329,0.98,0.86,5.6
8,4.3,0.540,0.70,14.00,0.107,99.0,153.5,0.01347,0.65,0.70,5.5
9,2.5,0.120,0.20,9.00,0.017,33.0,54.0,0.00735,0.21,0.25,2.5

In [5]:
wwines.agg('mean')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
quality,,,,,,,,,,,
3,7.600000,0.333250,0.336000,6.392500,0.054300,53.325000,170.600000,0.994884,3.187500,0.474500,10.345000
4,7.129448,0.381227,0.304233,4.628221,0.050098,23.358896,125.279141,0.994277,3.182883,0.476135,10.152454
5,6.933974,0.302011,0.337653,7.334969,0.051546,36.432052,150.904598,0.995263,3.168833,0.482203,9.808840
6,6.837671,0.260564,0.338025,6.441606,0.045217,35.650591,137.047316,0.993961,3.188599,0.491106,10.575372
7,6.734716,0.262767,0.325625,5.186477,0.038191,34.125568,125.114773,0.992452,3.213898,0.503102,11.367936
8,6.657143,0.277400,0.326514,5.671429,0.038314,36.720000,126.165714,0.992236,3.218686,0.486229,11.636000
9,7.420000,0.298000,0.386000,4.120000,0.027400,33.400000,116.000000,0.991460,3.308000,0.466000,12.180000